
server {

    listen 80;

    server_name app3.localhost;

    location / {

        proxy_pass http://app_3-backend-1:3000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    }

}


server {

    listen 80;

    server_name app2.localhost;

    location / {

        proxy_pass http://app_2-backend-1:3000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    }

}


server {

    listen 80;

    server_name app1.localhost;

    location / {

        proxy_pass http://app_1-backend-1:3000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    }

}
